"""empty message

Revision ID: 9f1c68019eb8
Revises: None
Create Date: 2018-03-16 21:19:01.219387

"""

# revision identifiers, used by Alembic.
revision = '9f1c68019eb8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
