"""empty message

Revision ID: b0cad8c41bd4
Revises: 18c931f6ddf5
Create Date: 2018-03-17 22:33:12.239943

"""

# revision identifiers, used by Alembic.
revision = 'b0cad8c41bd4'
down_revision = '18c931f6ddf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('resource_description', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('resource_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'resource_name')
    op.drop_column('resources', 'resource_description')
    op.drop_column('groups', 'group_name')
    ### end Alembic commands ###
