"""empty message

Revision ID: b486bbb95477
Revises: b0cad8c41bd4
Create Date: 2018-03-18 12:48:51.799111

"""

# revision identifiers, used by Alembic.
revision = 'b486bbb95477'
down_revision = 'b0cad8c41bd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_description')
    ### end Alembic commands ###
