"""empty message

Revision ID: db2f05fa675f
Revises: 00ae97767186
Create Date: 2018-03-17 19:17:26.030160

"""

# revision identifiers, used by Alembic.
revision = 'db2f05fa675f'
down_revision = '00ae97767186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    ### end Alembic commands ###
